Iter9 is done
bobgromozeka/metrics pull request #9
Opened 2023-06-27 15:16 UTC by bobgromozeka

2023-06-30 09:38 UTC, rktkov requested changes

2023-06-30 09:38 UTC, rktkov commented on internal/server/storage/storage.go
> +		Listeners: map[Event][]func(){},
Это место протекания функционала и размытие ответственности. Выполнение коллбек функции будет происходить в контексте хранилища и может привести к непредсказуемому поведению самого хранилища (я думаю об ошибках в коллбеках).
Уведомление о событии внутри хранилища не должно происходить через передачу потока управления, а через передачу данных, т.е. некого сигнала.

2023-06-30 09:38 UTC, rktkov commented on internal/server/storage/storage.go
> +func (s MemStorage) Listen(event Event, callbacks ...func()) {
Метод не является интерфейсным, т.е. о нем не будут знать клиенты, которые взаимодействуют с хранилищем через открытое АПИ.

2023-06-30 09:38 UTC, rktkov commented on internal/server/storage/storage.go
> +func (s MemStorage) fireEvent(event Event) {
Я бы все вот это удалял.

2023-06-30 09:38 UTC, rktkov commented on internal/server/server.go
> +type FileStorageSettings struct {
Стоит вынести эту структуру в отдельный пакет конфиг или сеттингс.

2023-06-30 09:38 UTC, rktkov commented on internal/server/server.go
> +			if restoreErr := s.RestoreFrom(fss.Path); restoreErr != nil {
Когда мы добавим тип хранения БД, то нам придется переписывать этот код. Стоит логику восстановления и сохранения из/в файл вынести внутрь реализации файлового хранилища и не давать внешним клиентам ей управлять.

2023-06-30 09:38 UTC, rktkov commented on internal/server/server.go
> +func setPersistence(s storage.MemStorage, filePath string, interval uint) error {
см. комментарий выше. Спрятав эту логику можно будет удалить и логику с коллбеками.

2023-06-30 09:38 UTC, rktkov commented on internal/server/middlewares/log.go
> +func WithLogging(f http.Handler) http.Handler {
Я бы оставил в этом пакете только этот метод. А код инициализации и работы с логами вынес бы в отдельный внутренний пакет - log

2023-06-30 09:38 UTC, rktkov commented on internal/server/middlewares/gzip.go
> +func Gzippify(next http.Handler) http.Handler {
см. комменатрий в мидлвере лога.

2023-06-30 09:38 UTC, rktkov commented on cmd/server/flags.go
> +var storeInterval uint
Это можно уже делать отдельной структурой и уносить в пакет конфиг или сеттингс.

2023-07-06 11:21 UTC, rktkov approved these changes
Код в комментарии стоит поправить к следующему ревью.

2023-07-06 11:21 UTC, rktkov commented on internal/server/storage/persistent.go
> +func WithPersistence(config PersistenceSettings) func(Storage) Storage {
Не вижу смысла возвращать функцию, которая сразу же вызывается. Может стоит изменить сигнару withPersistence, с делать ее NewPersistanceSotrage и вторым аргументом принимать  Storage, а в результате работы уже возвращать упакованную в новую структуру с интерфейсом Storage.

2023-07-06 11:36 UTC, bobgromozeka commented on internal/server/storage/persistent.go
> +func WithPersistence(config PersistenceSettings) func(Storage) Storage {
Да, хорошо, переделаю. Возврат функций очень часто в JS используется, уже привычка, буду перестраиваться на go

2023-07-06 11:51 UTC, merged